Feat: callbacks
aisingapore/PeekingDuck pull request #712
Opened 2022-10-13 07:12 UTC by liyier90

Enables users to attach callback functions to nodes to be run at certain points/events in the pipeline.

**Implemented events**:
- `run_begin`: Before `Node.run()`
- `run_end`: After `Node.run()`

**Supported callback types**:
- Pure function
- Class methods
- Static methods
- Instance methods (require instantiating the object in the callback script)

**UI**:
Users will specify callbacks for the node under the `callbacks` config key. Each callback is specified as:
```
callback definition = module part, "::", callback part
module part         = { subdir name, "." }, script name
callback part       = function
                     | class name, "::" , method
                     | instance name, "::", instance method

script name     = ? name of callback Python script ?
subdir name     = ? name of individual subdirectory folders relative to `callbacks` folder ?
class name      = ? name of class which contains the callback methods ?
instance name   = ? name of instantiated object which contains the 
function        = ? name of callback function ?
method          = ? name of class/static methods ?
instance method = ? name of instance method ?
```

Incorrect callback definitions are skipped with a warning log, program is not halted.

**Implementation detail**:
In `_edit_config()` of both `AbstractNode` and `DeclarativeLoader`, avoid going deeper into nested dictionary if the key is `callbacks`. This allows us to define the callbacks config in PeekingDuck as
```
callbacks: {}
```
and in pipeline config as
```
- node.name:
    callbacks:
      run_begin: ["callback::definition]
```
This allows us to implement more callback events in the future without have to add the event key to all the config files in PeekingDuck.

**Sample usage**:
Extract [callbacks.zip](https://github.com/aisingapore/PeekingDuck/files/9771643/callbacks.zip) into your project directory. Ensure that the `callbacks` directory is at the same level as `dev_callback.yml`. You should have the following directory layout:
```
project_dir
+-callbacks
| +-cb_dir
| +-my_callbacks.py
| \-sql_callback.py
+-dev_callback.yml
\-...
```

Run `dev_callback.yml` and you should see logging outputs such as
- `called 1` from `callback_1()` in `my_callbacks.py`
- `called z` from `cb_1()` in `cb_dir/mycb.py`
- `Suppressing logging` from `MyCallback.callback_2()` in my_callbacks.py`
- `Exceed zone limit ...` from `MyCallback.callback_3()` in `my_callbacks.py`
- `Update db with frame_count ...` from `cb_obj.track_count_callback()` in `sql_callback.py`

**Additional changes**:
- Refactored depracation code into separate methods (for ease of removal in the future)
- Removed `key` argument from `obj_det_class_name_to_id()`

2022-11-04 01:53 UTC, ongtw commented
Can you write up a tutorial `Using Callbacks` under the `Peaking Duck` tutorial section on using callbacks and giving some sample codes/pipelines as illustrations?

2022-11-09 01:14 UTC, liyier90 commented
Added a "Using Callbacks" section to Peaking Duck tutorial. Includes:
- tutorial to go over the implemented events and callback definition
- tutorial to replicate the "Interfacing with SQL" tutorial, replacing the `output.sqlite` custom node with a callback

2022-12-01 07:08 UTC, ongtw requested changes
Good work on pipeline callback.
Have some suggestions on improving the tutorial.

2022-12-01 07:08 UTC, ongtw commented on peekingduck/nodes/callback_list.py
> +                definitions. Each callback defintion should contain:
Typo: `defintion`

2022-12-01 07:08 UTC, ongtw commented on peekingduck/nodes/callback_list.py
> +    """Imports module from the specified location without haivng to modify
Typo: `haivng`

2022-12-01 07:08 UTC, ongtw commented on docs/source/tutorials/04_peaking_duck.rst
> +given the following directory structure and file contents:
We should specify that for `instance_name::instance_method`, the instance object has to be in the script's global scope (c.f. line 692 below).
For example, if `class A` has a method `A.f()` and an instance object `obj` is created within `A.f()`, then `obj::obj_method` would not work as `obj` cannot be "seen".

2022-12-01 07:08 UTC, ongtw commented on peekingduck/utils/detect_id_mapper.py
> +    return obj_ids_sorted_list
Need to update function return signature in line 84 above.

2022-12-01 07:08 UTC, ongtw commented on docs/source/tutorials/04_peaking_duck.rst
> +      - input.visual:
Remove ending comma

2022-12-01 07:08 UTC, ongtw commented on docs/source/tutorials/04_peaking_duck.rst
> +      - model.posenet
Need ending comma.

2022-12-01 07:08 UTC, ongtw commented on docs/source/tutorials/04_peaking_duck.rst
> +            run_end: [<callback 2>]
Can change above to `[<callback 2> <callback 3> <callback 4>]` to explicitly illustrate that we support a list of callbacks.

2022-12-01 07:08 UTC, ongtw commented on docs/source/tutorials/04_peaking_duck.rst
> +      - output.screen
The word `callback` appears many times in different forms, which can be hard to read and confusing.
Would like to suggest refactoring `my_callback_function`, `my_callback_static_method`, `my_callback_class_method`, `my_callback_instance_method` as shown in below image.
Also added some code to access and print `data_pool` contents.

![image](https://user-images.githubusercontent.com/13075447/204987710-5b98f09d-6d93-4177-8090-894bb82dbf48.png)

Will have to update the following table accordingly.

2022-12-01 08:46 UTC, liyier90 commented on peekingduck/nodes/callback_list.py
> +                definitions. Each callback defintion should contain:
Fixed

2022-12-01 08:46 UTC, liyier90 commented on peekingduck/nodes/callback_list.py
> +    """Imports module from the specified location without haivng to modify
Fixed

2022-12-01 08:49 UTC, liyier90 commented on peekingduck/utils/detect_id_mapper.py
> +    return obj_ids_sorted_list
Fixed

2022-12-01 08:58 UTC, liyier90 commented on docs/source/tutorials/04_peaking_duck.rst
> +given the following directory structure and file contents:
Added clarifition while referencing example below.

2022-12-01 08:58 UTC, liyier90 commented on docs/source/tutorials/04_peaking_duck.rst
> +      - input.visual:
Removed

2022-12-01 08:58 UTC, liyier90 commented on docs/source/tutorials/04_peaking_duck.rst
> +      - model.posenet
Added

2022-12-01 09:10 UTC, liyier90 commented on docs/source/tutorials/04_peaking_duck.rst
> +            run_end: [<callback 2>]
Changed

2022-12-01 09:42 UTC, liyier90 commented on docs/source/tutorials/04_peaking_duck.rst
> +      - output.screen
Updated

2022-12-02 01:59 UTC, ongtw commented on peekingduck/nodes/callback_list.py
> +                definitions. Each callback defintion should contain:
Looks like the changes have not been saved. Once this is corrected, can merge.

2022-12-02 02:09 UTC, liyier90 commented on peekingduck/nodes/callback_list.py
> +                definitions. Each callback defintion should contain:
Oh sorry, I misunderstood this, changed `definitions -> definition` initally.

Corrected `defintion -> definition`

2022-12-02 04:15 UTC, merged